version: "3.0"
services:
  memos:
    image: neosmemo/memos:latest
#    container_name: memos
    volumes:
      - ./memos/:/var/opt/memos
#    ports:
#      - 5230:5230
    networks:
      - traefik-network
    deploy:
      replicas: 1
      labels:
        - "traefik.enable=true"
        - "traefik.http.services.memos.loadbalancer.server.port=5230"
        - "traefik.http.routers.memos.rule=Host(`memos.dgital.pro`)"
        - "traefik.http.routers.memos.entrypoints=web-secured"
        - "traefik.http.routers.memos.tls.certresolver=mytlschallenge"
      placement:
        constraints:
          - "node.role == manager"
networks:
  traefik-network:
    external: true
