version: '3'

services:
  confluence:
    image: atlassian/confluence-server:6.11
#    restart: always
    ports:
      - 52192
    volumes:
      - ./confluence/:/var/atlassian/application-data/confluence
    networks:
      - traefik-network
#    environment:
#      - CATALINA_CONNECTOR_PROXYNAME=confluence.dgital.pro
#      - CATALINA_CONNECTOR_PROXYPORT=443
#      - CATALINA_CONNECTOR_SCHEME=https
#      - CATALINA_CONNECTOR_SECURE=true
    deploy:
      # this basically says that only deploy 1 per node in every manager node
      # and reserve 128MB of ram to it, also limit the memory to 256MB
      placement:
        constraints:
          - "node.role == manager"
      labels:
        - traefik.enable=true
        - traefik.http.routers.confluence.rule=Host(`confluence.dgital.pro`)
        - traefik.http.routers.confluence.entrypoints=web-secured
        - traefik.http.routers.confluence.tls=true
        - traefik.http.routers.confluence.tls.certresolver=mytlschallenge
        - traefik.http.services.confluence.loadbalancer.server.port=52192

  postgres:
    image: postgres:9.6
    restart: always
    volumes:
      - ./pgdata/:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=confluence
      - POSTGRES_DB=confluence
      - POSTGRES_PASSWORD=123456789
    networks:
      - traefik-network
    deploy:
      # this basically says that only deploy 1 per node in every manager node
      # and reserve 128MB of ram to it, also limit the memory to 256MB
      placement:
        constraints:
          - "node.role == manager"

networks:
  traefik-network:
    external: true
